services:
  blue:
    image: zeroTimeDeploy:latest
    container_name: blue
    restart: always
    ports:
      - 8081:80
  green:
    image: zeroTimeDeploy:latest
    container_name: green
    restart: always
    ports:
      - 8082:80
