spring:
  profiles:
    active: blue

---
spring:
  config:
    activate:
      on-profile: blue
server:
  port: 8080  # 모든 프로필에서 8080 포트로 통일

---
spring:
  config:
    activate:
      on-profile: green
server:
  port: 8080  # 모든 프로필에서 8080 포트로 통일

