spring:
  profiles:
    active: blue

---
spring:
  config:
    activate:
      on-profile: blue
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: green
server:
  port: 8082

